twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      safety_stop:
        topic   : safety_stop
        timeout : 0.5
        priority: 100
      teleop:
        topic   : cmd_vel
        timeout : 0.5
        priority: 30
      pure_pursuit:
        topic   : cmd_vel_ppc
        timeout : 0.5
        priority: 20
    output_topic: cmd_vel_out 

